### ISSUE TITLE
Install path unclear

### ISSUE THREAD

**Issue by garyritchie** [armory3d/logic_pack#10]
Please add just a little more detail on where to install/enable these nodes. Consider those new to Armory.

**Comment by luboslenco** [comment]
Instructions updated, hope that helps!

**Comment by garyritchie** [comment]
Well, that was fast! Thanks!

**Comment by softyoda** [comment]
Install path still unclear. I'm on windows, I created as requested a folder named "Libraries" next to my".blend" but if I unzip the content of all github, i have a /source/armory/logicnodes path, and the blender.py is in the same place as readme.md

After talking with members of the armory community discord, I finally found out where the problem was (you only needed to have a logicnodes file with all the.hx and the blender.py inside)

**Comment by luboslenco** [comment]
Sorry I am not sure I understand. If you downloaded .zip instead of git clone then just extracting the `logic_pack-master.zip` into `Libraries` folder should work?

![capture](https://user-images.githubusercontent.com/3685704/41467582-5703ab8e-70a7-11e8-87bc-06cc851d85b3.PNG)

**Comment by softyoda** [comment]
.... I just tried to make a video to show that simply unzipping all the files, was not working.

But it worked ...


I don't understand why I had to modify the tree structure to make it work with my other project, whereas on a blank project like this, it works.

On my old project, the files .hx and.py must all be in` .blendfolder/Libraries/logicnodes/logicnodes`
And only unzipping all github doesn't work.

And in my new test project the default path `.blendfolder/Libraries/logic_pack-master/Sources/armory/logicnode/files.hx`
and `.blendfolder/Librairies/Bibliothèques/logic_pack-master/blender.py`
(like github tree structure)
